language: bash
sudo: required

services:
  - docker

before_install: 
  - docker build -t tumgis/ctb-quantized-mesh .

script:
  - docker run --rm --name ctb tumgis/ctb-quantized-mesh "ctb-tile" "--version" | grep -i "[0-9]\.[0-9]\.[0-9]"
  - docker run --rm --name ctb tumgis/ctb-quantized-mesh "gdalbuildvrt" "--version" | grep -i "GDAL [0-9]\.[0-9]\.[0-9].*"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tumgis/ctb-quantized-mesh
  
notifications:
    slack: tum-gis:Z32lHXJDXaycOn4643NHSXaT
    on_success: change
    on_failure: always
